apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  selector:
    app: myapp-nginx   # ye label pod.yaml me hona chahiye
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
      name: http
      
  type: LoadBalancer
